---
version: "3"
services:
  vagaBot:
    image: 'vaga_bot'
    command: "sleep infinity"
    volumes:
      - ./app:/etc/app
    working_dir: /etc/app
    build:
      context: ./dockerImages
      dockerfile: vagaBot.dockerfile
    container_name: vaga-bot
